### PR TITLE
Restore the midroll link plugin file

### PR DESCRIPTION
**Pull request by gbuilds**
Puts back the midroll plugin.js file for folks who are using the lab and haven't switched to annotation links yet to make for a gentler transition over.

@jeffvincent 
Wondering if I need to do anything else for fast.wistia.net/mid-roll-links/plugin.js to deliver this script?

### CODE REVIEW

**Comment by jeffvincent** [comment]
Can you expand on what a "gentler transition" means?

**Comment by gbuilds** [comment]
Well, right now a particular high volume customer has a bunch of live
midroll links that don't work, which as you can imagine is concerning to
them.

It'd be nice if we could host the script while they move their stuff to
annotation links.

Other customers with live midroll links probably don't realize their links
aren't working right now :/ Maybe it's possible we email them.

**Comment by jeffvincent** [comment]
Ohh - hmm, it was not my intention to make live ones fail! Good call :smile:

**Comment by gbuilds** [comment]
Yep! I figured :) I think putting this file back should fix that, but
wondering if there's anything to do to make sure fastly has this script?

**Comment by jeffvincent** [comment]
In the labs readme, there are directions on purging from Fastly. I don't remember exactly what I did there.

**Comment by jeffvincent** [comment]
This makes me think we should bring the other js back as well!

**Comment by bschwartz** [comment]
Good catch @gbuilds! Once those plugin js files are back for each we need to redeploy labs via the instructions in the readme. Shouldn't need to do anything with Fastly since we're not updating an existing script, just adding scripts.

**Comment by gbuilds** [comment]
Okay, adding the GA lab, video foam, & speakerdeck javascript files back in
too.

**Comment by jeffvincent** [comment]
Great work @gbuilds! Glad you caught that :smile_cat:

**Comment by gbuilds** [comment]
Thanks @jeffvincent Think we should be all good now!

**Pull request merged**
